export interface Employee {
  id: string
  name: string
  position: string
  department: string
  team?: string
  type: "executive" | "manager" | "employee" | "contractor"
  score?: number
}

export interface Department {
  id: string
  name: string
  manager: Employee
  teams: Team[]
  averageScore: number
}

export interface Team {
  id: string
  name: string
  manager: Employee
  members: Employee[]
  averageScore: number
}

export const organizationData: Department[] = [
  {
    id: "transport",
    name: "輸送事業部",
    manager: {
      id: "ikeda",
      name: "池田 直輝",
      position: "取締役部長",
      department: "輸送事業部",
      type: "executive",
      score: 82,
    },
    averageScore: 78,
    teams: [
      {
        id: "transport-1",
        name: "輸送第一課",
        manager: {
          id: "yamazaki",
          name: "山﨑 清志",
          position: "課長",
          department: "輸送事業部",
          team: "輸送第一課",
          type: "manager",
          score: 79,
        },
        averageScore: 78,
        members: [
          {
            id: "sada",
            name: "佐田 直澄",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 76,
          },
          {
            id: "takamatsu",
            name: "高松 克寿",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 81,
          },
          {
            id: "fukui",
            name: "福井 隼人",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 74,
          },
          {
            id: "nakamura",
            name: "中村 圭祐",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 78,
          },
          {
            id: "ishida",
            name: "石田 晋吾",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 80,
          },
          {
            id: "kaji",
            name: "加地 大悟",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 77,
          },
          {
            id: "sakotani",
            name: "迫谷 翠則",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 75,
          },
          {
            id: "kokubo",
            name: "小久保 康祐",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 79,
          },
          {
            id: "yasuba",
            name: "安場 功輝",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 82,
          },
          {
            id: "goto",
            name: "五藤 大斗",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 76,
          },
          {
            id: "nishiguchi-k",
            name: "西口 一瑠",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 78,
          },
          {
            id: "mori-k",
            name: "森 健仁",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "employee",
            score: 80,
          },
          {
            id: "yoshida",
            name: "吉田 誠宏",
            position: "運転委託",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "contractor",
            score: 73,
          },
          {
            id: "rakumarujaya",
            name: "ラクマルジャヤ・コディ",
            position: "運転委託",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "contractor",
            score: 75,
          },
          {
            id: "ozeki",
            name: "尾関 巧真",
            position: "運転委託",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "contractor",
            score: 74,
          },
          {
            id: "sugihara",
            name: "杉原 央崇",
            position: "運転委託",
            department: "輸送事業部",
            team: "輸送第一課",
            type: "contractor",
            score: 76,
          },
        ],
      },
      {
        id: "transport-2",
        name: "輸送第二課",
        manager: {
          id: "kitayama",
          name: "北山 尚哉",
          position: "課長",
          department: "輸送事業部",
          team: "輸送第二課",
          type: "manager",
          score: 75,
        },
        averageScore: 72,
        members: [
          {
            id: "kawabe",
            name: "河辺 豊",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 71,
          },
          {
            id: "matsumoto-k",
            name: "松本 一樹",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 73,
          },
          {
            id: "nawa",
            name: "名和 聡",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 70,
          },
          {
            id: "murata",
            name: "村田 哲男",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 74,
          },
          {
            id: "nambu",
            name: "南部 知加",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 72,
          },
          {
            id: "funato",
            name: "船戸 空海",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 71,
          },
          {
            id: "nishiguchi-t",
            name: "西口 朋弘",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 73,
          },
          {
            id: "murakami",
            name: "村上 外作",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 70,
          },
          {
            id: "nakajima",
            name: "中島 高明",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 75,
          },
          {
            id: "nishino",
            name: "西野 天華",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 72,
          },
          {
            id: "saito",
            name: "齊藤 真衣",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 71,
          },
          {
            id: "kishida",
            name: "岸田 理紗",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "employee",
            score: 74,
          },
          {
            id: "hashizume",
            name: "橋爪 弘輔",
            position: "運転委託",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "contractor",
            score: 69,
          },
          {
            id: "saso",
            name: "佐宗 大地",
            position: "運転委託",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "contractor",
            score: 70,
          },
          {
            id: "kamiyama",
            name: "神山 幸也",
            position: "運転委託",
            department: "輸送事業部",
            team: "輸送第二課",
            type: "contractor",
            score: 71,
          },
        ],
      },
      {
        id: "transport-3",
        name: "輸送第三課",
        manager: {
          id: "kitayama-2",
          name: "北山 尚哉",
          position: "課長",
          department: "輸送事業部",
          team: "輸送第三課",
          type: "manager",
          score: 83,
        },
        averageScore: 81,
        members: [
          {
            id: "matsumoto-s",
            name: "松本 真一郎",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第三課",
            type: "employee",
            score: 82,
          },
          {
            id: "murao",
            name: "村尾 尚輝",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第三課",
            type: "employee",
            score: 80,
          },
          {
            id: "mori-y",
            name: "森 嘉太",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第三課",
            type: "employee",
            score: 81,
          },
          {
            id: "wada",
            name: "和田 裕希",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第三課",
            type: "employee",
            score: 83,
          },
          {
            id: "koide",
            name: "小出 隆一",
            position: "現場担当",
            department: "輸送事業部",
            team: "輸送第三課",
            type: "employee",
            score: 79,
          },
        ],
      },
      {
        id: "admin",
        name: "管理課",
        manager: {
          id: "sato-s",
          name: "佐藤 栞",
          position: "課長",
          department: "輸送事業部",
          team: "管理課",
          type: "manager",
          score: 87,
        },
        averageScore: 85,
        members: [
          {
            id: "tanto",
            name: "丹藤 愛美子",
            position: "管理事務",
            department: "輸送事業部",
            team: "管理課",
            type: "employee",
            score: 84,
          },
          {
            id: "kawahara",
            name: "河原 惇汰",
            position: "管理事務",
            department: "輸送事業部",
            team: "管理課",
            type: "employee",
            score: 86,
          },
        ],
      },
    ],
  },
  {
    id: "farm",
    name: "実FARM事業",
    manager: {
      id: "sato-r",
      name: "佐藤 李典",
      position: "農園責任者",
      department: "実FARM事業",
      type: "manager",
      score: 78,
    },
    averageScore: 76,
    teams: [
      {
        id: "farm-team",
        name: "農園チーム",
        manager: {
          id: "sato-r",
          name: "佐藤 李典",
          position: "農園責任者",
          department: "実FARM事業",
          type: "manager",
          score: 78,
        },
        averageScore: 76,
        members: [
          {
            id: "shiraki",
            name: "白木 勢央",
            position: "スタッフ",
            department: "実FARM事業",
            type: "employee",
            score: 74,
          },
        ],
      },
    ],
  },
  {
    id: "twoeight",
    name: "TWO EIGHT事業",
    manager: {
      id: "hamada",
      name: "浜田 啓",
      position: "販売担当",
      department: "TWO EIGHT事業",
      type: "manager",
      score: 79,
    },
    averageScore: 79,
    teams: [],
  },
]

export const ceo: Employee = {
  id: "sato-k",
  name: "佐藤 恭太郎",
  position: "代表取締役社長",
  department: "経営",
  type: "executive",
  score: 88,
}
